#!/bin/zsh
#
# .zprofile - Zsh login config
#

# Editors
export EDITOR="${EDITOR:-vim}"
export VISUAL="${VISUAL:-vim}"
export PAGER="${PAGER:-less}"

# Remove duplicates from path arrays
typeset -gU path fpath

# PATH
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)